local_repository(
    name = "io_bazel_rules_dotnet_fsharp",
    path = ".."
)

load(
    "@io_bazel_rules_dotnet_fsharp//dotnet:fsharp.bzl",
    "fsharp_repositories",
    "paket_dependencies",
)

fsharp_repositories(use_local_mono = True)

paket_dependencies(
    name = "paket_deps",
    deps = """
source https://nuget.org/api/v2
framework: net46
nuget ExtCore
nuget Argu
    """,
)
