load(
    "@io_bazel_rules_dotnet_fsharp//dotnet:fsharp.bzl",
    "fsharp_library",
    "nuget_package",
)

fsharp_library(
    name = "lib",
    srcs = ["lib.fs"],
    visibility = ["//visibility:public"]
)
